#include "TokenKindUtil.hpp"
#include "lexer/Lexer.hpp"
#include <string_view>

namespace vnlc {
    std::string_view TokenKindUtil::toString(TokenKind kind) {
        switch (kind) {
            case TokenKind::IDENTIFIER:
                return "VnlcTokenKind::IDENTIFIER";
            case TokenKind::NUMBER:
                return "VnlcTokenKind::NUMBER";
            case TokenKind::CHAR:
                return "VnlcTokenKind::CHAR";
            case TokenKind::STRING:
                return "VnlcTokenKind::STRING";
            case TokenKind::VAR:
                return "VnlcTokenKind::VAR";
            case TokenKind::LET:
                return "VnlcTokenKind::LET";
            case TokenKind::CONST:
                return "VnlcTokenKind::CONST";
            case TokenKind::BYTE_TYPE:
                return "VnlcTokenKind::BYTE_TYPE";
            case TokenKind::SHORT_TYPE:
                return "VnlcTokenKind::SHORT_TYPE";
            case TokenKind::INT_TYPE:
                return "VnlcTokenKind::INT_TYPE";
            case TokenKind::LONG_TYPE:
                return "VnlcTokenKind::LONG_TYPE";
            case TokenKind::FLOAT_TYPE:
                return "VnlcTokenKind::FLOAT_TYPE";
            case TokenKind::DOUBLE_TYPE:
                return "VnlcTokenKind::DOUBLE_TYPE";
            case TokenKind::BOOL_TYPE:
                return "VnlcTokenKind::BOOL_TYPE";
            case TokenKind::STRING_TYPE:
                return "VnlcTokenKind::STRING_TYPE";
            case TokenKind::FUNC:
                return "VnlcTokenKind::FUNC";
            case TokenKind::INIT:
                return "VnlcTokenKind::INIT";
            case TokenKind::RETURN:
                return "VnlcTokenKind::RETURN";
            case TokenKind::IF:
                return "VnlcTokenKind::IF";
            case TokenKind::ELSE:
                return "VnlcTokenKind::ELSE";
            case TokenKind::FOR:
                return "VnlcTokenKind::FOR";
            case TokenKind::WHILE:
                return "VnlcTokenKind::WHILE";
            case TokenKind::LABEL:
                return "VnlcTokenKind::LABEL";
            case TokenKind::BREAK:
                return "VnlcTokenKind::BREAK";
            case TokenKind::CONTINUE:
                return "VnlcTokenKind::CONTINUE";
            case TokenKind::SWITCH:
                return "VnlcTokenKind::SWITCH";
            case TokenKind::CASE:
                return "VnlcTokenKind::CASE";
            case TokenKind::DEFAULT:
                return "VnlcTokenKind::DEFAULT";
            case TokenKind::WHEN:
                return "VnlcTokenKind::WHEN";
            case TokenKind::CONTEXT:
                return "VnlcTokenKind::CONTEXT";
            case TokenKind::VOID:
                return "VnlcTokenKind::VOID";
            case TokenKind::NATIVE:
                return "VnlcTokenKind::NATIVE";
            case TokenKind::CALLEE:
                return "VnlcTokenKind::CALLEE";
            case TokenKind::IN:
                return "VnlcTokenKind::IN";
            case TokenKind::RELOAD:
                return "VnlcTokenKind::RELOAD";
            case TokenKind::CLASS:
                return "VnlcTokenKind::CLASS";
            case TokenKind::INTERFACE:
                return "VnlcTokenKind::INTERFACE";
            case TokenKind::ABSTRACT:
                return "VnlcTokenKind::ABSTRACT";
            case TokenKind::TYPE:
                return "VnlcTokenKind::TYPE";
            case TokenKind::ENUM:
                return "VnlcTokenKind::ENUM";
            case TokenKind::RECORD:
                return "VnlcTokenKind::RECORD";
            case TokenKind::EXTENDS:
                return "VnlcTokenKind::EXTENDS";
            case TokenKind::IMPLEMENTS:
                return "VnlcTokenKind::IMPLEMENTS";
            case TokenKind::THIS:
                return "VnlcTokenKind::THIS";
            case TokenKind::SUPER:
                return "VnlcTokenKind::SUPER";
            case TokenKind::PRIVATE:
                return "VnlcTokenKind::PRIVATE";
            case TokenKind::PROTECTED:
                return "VnlcTokenKind::PROTECTED";
            case TokenKind::PUBLIC:
                return "VnlcTokenKind::PUBLIC";
            case TokenKind::READONLY:
                return "VnlcTokenKind::READONLY";
            case TokenKind::STATIC:
                return "VnlcTokenKind::STATIC";
            case TokenKind::INSTANCEOF:
                return "VnlcTokenKind::INSTANCEOF";
            case TokenKind::FINAL:
                return "VnlcTokenKind::FINAL";
            case TokenKind::OVERRIDE:
                return "VnlcTokenKind::OVERRIDE";
            case TokenKind::NONE:
                return "VnlcTokenKind::NONE";
            case TokenKind::TRUE:
                return "VnlcTokenKind::TRUE";
            case TokenKind::FALSE:
                return "VnlcTokenKind::FALSE";
            case TokenKind::IMPORT:
                return "VnlcTokenKind::IMPORT";
            case TokenKind::EXPORT:
                return "VnlcTokenKind::EXPORT";
            case TokenKind::AS:
                return "VnlcTokenKind::AS";
            case TokenKind::MODULE:
                return "VnlcTokenKind::MODULE";
            case TokenKind::PARENT:
                return "VnlcTokenKind::PARENT";
            case TokenKind::LAMBDA:
                return "VnlcTokenKind::LAMBDA";
            case TokenKind::COMMAND:
                return "VnlcTokenKind::COMMAND";
            case TokenKind::ASYNC:
                return "VnlcTokenKind::ASYNC";
            case TokenKind::AWAIT:
                return "VnlcTokenKind::AWAIT";
            case TokenKind::GENERATOR:
                return "VnlcTokenKind::GENERATOR";
            case TokenKind::YIELD:
                return "VnlcTokenKind::YIELD";
            case TokenKind::FROM:
                return "VnlcTokenKind::FROM";
            case TokenKind::DECORATOR:
                return "VnlcTokenKind::DECORATOR";
            case TokenKind::DECORATE:
                return "VnlcTokenKind::DECORATE";
            case TokenKind::PANIC:
                return "VnlcTokenKind::PANIC";
            case TokenKind::ASSERT:
                return "VnlcTokenKind::ASSERT";
            case TokenKind::TYPEOF:
                return "VnlcTokenKind::TYPEOF";
            case TokenKind::DEFER:
                return "VnlcTokenKind::DEFER";
            case TokenKind::ASSET:
                return "VnlcTokenKind::ASSET";
            case TokenKind::DEFINE:
                return "VnlcTokenKind::DEFINE";
            case TokenKind::METADATA:
                return "VnlcTokenKind::METADATA";
            case TokenKind::PLUS:
                return "VnlcTokenKind::PLUS";
            case TokenKind::MINUS:
                return "VnlcTokenKind::MINUS";
            case TokenKind::ASTERISK:
                return "VnlcTokenKind::ASTERISK";
            case TokenKind::SLASH:
                return "VnlcTokenKind::SLASH";
            case TokenKind::DOUBLE_SLASH:
                return "VnlcTokenKind::DOUBLE_SLASH";
            case TokenKind::PERCENT:
                return "VnlcTokenKind::PERCENT";
            case TokenKind::DOUBLE_ASTERISK:
                return "VnlcTokenKind::DOUBLE_ASTERISK";
            case TokenKind::PLUS_EQUAL:
                return "VnlcTokenKind::PLUS_EQUAL";
            case TokenKind::MINUS_EQUAL:
                return "VnlcTokenKind::MINUS_EQUAL";
            case TokenKind::ASTERISK_EQUAL:
                return "VnlcTokenKind::ASTERISK_EQUAL";
            case TokenKind::SLASH_EQUAL:
                return "VnlcTokenKind::SLASH_EQUAL";
            case TokenKind::DOUBLE_SLASH_EQUAL:
                return "VnlcTokenKind::DOUBLE_SLASH_EQUAL";
            case TokenKind::PERCENT_EQUAL:
                return "VnlcTokenKind::PERCENT_EQUAL";
            case TokenKind::DOUBLE_ASTERISK_EQUAL:
                return "VnlcTokenKind::DOUBLE_ASTERISK_EQUAL";
            case TokenKind::EQUAL:
                return "VnlcTokenKind::EQUAL";
            case TokenKind::DOUBLE_QUESTION_EQUAL:
                return "VnlcTokenKind::DOUBLE_QUESTION_EQUAL";
            case TokenKind::DOUBLE_EQUAL:
                return "VnlcTokenKind::DOUBLE_EQUAL";
            case TokenKind::EXCLAMATION_EQUAL:
                return "VnlcTokenKind::EXCLAMATION_EQUAL";
            case TokenKind::RIGHT_ANGLE:
                return "VnlcTokenKind::RIGHT_ANGLE";
            case TokenKind::RIGHT_ANGLE_EQUAL:
                return "VnlcTokenKind::RIGHT_ANGLE_EQUAL";
            case TokenKind::LEFT_ANGLE:
                return "VnlcTokenKind::LEFT_ANGLE";
            case TokenKind::LEFT_ANGLE_EQUAL:
                return "VnlcTokenKind::LEFT_ANGLE_EQUAL";
            case TokenKind::DOUBLE_AMPERSAND:
                return "VnlcTokenKind::DOUBLE_AMPERSAND";
            case TokenKind::DOUBLE_PIPE:
                return "VnlcTokenKind::DOUBLE_PIPE";
            case TokenKind::DOUBLE_QUESTION:
                return "VnlcTokenKind::DOUBLE_QUESTION";
            case TokenKind::EXCLAMATION:
                return "VnlcTokenKind::EXCLAMATION";
            case TokenKind::ARROW:
                return "VnlcTokenKind::ARROW";
            case TokenKind::AMPERSAND:
                return "VnlcTokenKind::AMPERSAND";
            case TokenKind::PIPE:
                return "VnlcTokenKind::PIPE";
            case TokenKind::CARET:
                return "VnlcTokenKind::CARET";
            case TokenKind::TILDE:
                return "VnlcTokenKind::TILDE";
            case TokenKind::DOUBLE_LEFT_ANGLE:
                return "VnlcTokenKind::DOUBLE_LEFT_ANGLE";
            case TokenKind::DOUBLE_RIGHT_ANGLE:
                return "VnlcTokenKind::DOUBLE_RIGHT_ANGLE";
            case TokenKind::TRIPLE_RIGHT_ANGLE:
                return "VnlcTokenKind::TRIPLE_RIGHT_ANGLE";
            case TokenKind::AMPERSAND_EQUAL:
                return "VnlcTokenKind::AMPERSAND_EQUAL";
            case TokenKind::PIPE_EQUAL:
                return "VnlcTokenKind::PIPE_EQUAL";
            case TokenKind::CARET_EQUAL:
                return "VnlcTokenKind::CARET_EQUAL";
            case TokenKind::DOUBLE_LEFT_ANGLE_EQUAL:
                return "VnlcTokenKind::DOUBLE_LEFT_ANGLE_EQUAL";
            case TokenKind::DOUBLE_RIGHT_ANGLE_EQUAL:
                return "VnlcTokenKind::DOUBLE_RIGHT_ANGLE_EQUAL";
            case TokenKind::TRIPLE_RIGHT_ANGLE_EQUAL:
                return "VnlcTokenKind::TRIPLE_RIGHT_ANGLE_EQUAL";
            case TokenKind::DOT:
                return "VnlcTokenKind::DOT";
            case TokenKind::COMMA:
                return "VnlcTokenKind::COMMA";
            case TokenKind::SEMICOLON:
                return "VnlcTokenKind::SEMICOLON";
            case TokenKind::COLON:
                return "VnlcTokenKind::COLON";
            case TokenKind::DOUBLE_COLON:
                return "VnlcTokenKind::DOUBLE_COLON";
            case TokenKind::QUESTION:
                return "VnlcTokenKind::QUESTION";
            case TokenKind::QUESTION_DOT:
                return "VnlcTokenKind::QUESTION_DOT";
            case TokenKind::EXCLAMATION_DOT:
                return "VnlcTokenKind::EXCLAMATION_DOT";
            case TokenKind::DOUBLE_DOT:
                return "VnlcTokenKind::DOUBLE_DOT";
            case TokenKind::TRIPLE_DOT:
                return "VnlcTokenKind::TRIPLE_DOT";
            case TokenKind::LEFT_PARENTHESIS:
                return "VnlcTokenKind::LEFT_PARENTHESIS";
            case TokenKind::RIGHT_PARENTHESIS:
                return "VnlcTokenKind::RIGHT_PARENTHESIS";
            case TokenKind::LEFT_BRACE:
                return "VnlcTokenKind::LEFT_BRACE";
            case TokenKind::RIGHT_BRACE:
                return "VnlcTokenKind::RIGHT_BRACE";
            case TokenKind::LEFT_BRACKET:
                return "VnlcTokenKind::LEFT_BRACKET";
            case TokenKind::RIGHT_BRACKET:
                return "VnlcTokenKind::RIGHT_BRACKET";
            case TokenKind::SELECTOR_PREFIX:
                return "VnlcTokenKind::SELECTOR_PREFIX";
            case TokenKind::INTERPOLATION_START:
                return "VnlcTokenKind::INTERPOLATION_START";
            case TokenKind::SINGLE_LINE_COMMENT:
                return "VnlcTokenKind::SINGLE_LINE_COMMENT";
            case TokenKind::MULTI_LINE_COMMENT:
                return "VnlcTokenKind::MULTI_LINE_COMMENT";
            case TokenKind::BLANK:
                return "VnlcTokenKind::BLANK";
            case TokenKind::NEWLINE:
                return "VnlcTokenKind::NEWLINE";
            case TokenKind::LEXICAL_ERROR:
                return "VnlcTokenKind::LEXICAL_ERROR";
            case TokenKind::END_OF_FILE:
                return "VnlcTokenKind::END_OF_FILE";
            default:
                return "Unknown VnlcTokenKind";
        }
    }

    bool TokenKindUtil::isGeneralizedIdentifier(TokenKind kind) {
        if (kind == TokenKind::IDENTIFIER) {
            return true;
        }

        bool isKeyword = false;

        for (auto& [keyword, keywordKind] : Lexer::keywords) {
            if (kind == keywordKind) {
                isKeyword = true;
                break;
            }
        }

        return isKeyword;
    }
} // namespace vnlc
