#include "TokenTypeUtil.hpp"
#include "lexer/Lexer.hpp"
#include <string_view>

namespace vnlc {
    std::string_view TokenTypeUtil::toString(TokenType type) {
        switch (type) {
            case TokenType::IDENTIFIER:
                return "VnlcTokenType::IDENTIFIER";
            case TokenType::NUMBER:
                return "VnlcTokenType::NUMBER";
            case TokenType::CHAR:
                return "VnlcTokenType::CHAR";
            case TokenType::STRING:
                return "VnlcTokenType::STRING";
            case TokenType::VAR:
                return "VnlcTokenType::VAR";
            case TokenType::LET:
                return "VnlcTokenType::LET";
            case TokenType::CONST:
                return "VnlcTokenType::CONST";
            case TokenType::BYTE_TYPE:
                return "VnlcTokenType::BYTE_TYPE";
            case TokenType::SHORT_TYPE:
                return "VnlcTokenType::SHORT_TYPE";
            case TokenType::INT_TYPE:
                return "VnlcTokenType::INT_TYPE";
            case TokenType::LONG_TYPE:
                return "VnlcTokenType::LONG_TYPE";
            case TokenType::FLOAT_TYPE:
                return "VnlcTokenType::FLOAT_TYPE";
            case TokenType::DOUBLE_TYPE:
                return "VnlcTokenType::DOUBLE_TYPE";
            case TokenType::BOOL_TYPE:
                return "VnlcTokenType::BOOL_TYPE";
            case TokenType::STRING_TYPE:
                return "VnlcTokenType::STRING_TYPE";
            case TokenType::FUNC:
                return "VnlcTokenType::FUNC";
            case TokenType::INIT:
                return "VnlcTokenType::INIT";
            case TokenType::RETURN:
                return "VnlcTokenType::RETURN";
            case TokenType::IF:
                return "VnlcTokenType::IF";
            case TokenType::ELSE:
                return "VnlcTokenType::ELSE";
            case TokenType::FOR:
                return "VnlcTokenType::FOR";
            case TokenType::WHILE:
                return "VnlcTokenType::WHILE";
            case TokenType::LABEL:
                return "VnlcTokenType::LABEL";
            case TokenType::BREAK:
                return "VnlcTokenType::BREAK";
            case TokenType::CONTINUE:
                return "VnlcTokenType::CONTINUE";
            case TokenType::SWITCH:
                return "VnlcTokenType::SWITCH";
            case TokenType::CASE:
                return "VnlcTokenType::CASE";
            case TokenType::DEFAULT:
                return "VnlcTokenType::DEFAULT";
            case TokenType::WHEN:
                return "VnlcTokenType::WHEN";
            case TokenType::CONTEXT:
                return "VnlcTokenType::CONTEXT";
            case TokenType::VOID:
                return "VnlcTokenType::VOID";
            case TokenType::NATIVE:
                return "VnlcTokenType::NATIVE";
            case TokenType::CALLEE:
                return "VnlcTokenType::CALLEE";
            case TokenType::IN:
                return "VnlcTokenType::IN";
            case TokenType::RELOAD:
                return "VnlcTokenType::RELOAD";
            case TokenType::CLASS:
                return "VnlcTokenType::CLASS";
            case TokenType::INTERFACE:
                return "VnlcTokenType::INTERFACE";
            case TokenType::ABSTRACT:
                return "VnlcTokenType::ABSTRACT";
            case TokenType::TYPE:
                return "VnlcTokenType::TYPE";
            case TokenType::ENUM:
                return "VnlcTokenType::ENUM";
            case TokenType::RECORD:
                return "VnlcTokenType::RECORD";
            case TokenType::EXTENDS:
                return "VnlcTokenType::EXTENDS";
            case TokenType::IMPLEMENTS:
                return "VnlcTokenType::IMPLEMENTS";
            case TokenType::THIS:
                return "VnlcTokenType::THIS";
            case TokenType::SUPER:
                return "VnlcTokenType::SUPER";
            case TokenType::PRIVATE:
                return "VnlcTokenType::PRIVATE";
            case TokenType::PROTECTED:
                return "VnlcTokenType::PROTECTED";
            case TokenType::PUBLIC:
                return "VnlcTokenType::PUBLIC";
            case TokenType::READONLY:
                return "VnlcTokenType::READONLY";
            case TokenType::STATIC:
                return "VnlcTokenType::STATIC";
            case TokenType::INSTANCEOF:
                return "VnlcTokenType::INSTANCEOF";
            case TokenType::FINAL:
                return "VnlcTokenType::FINAL";
            case TokenType::OVERRIDE:
                return "VnlcTokenType::OVERRIDE";
            case TokenType::NONE:
                return "VnlcTokenType::NONE";
            case TokenType::TRUE:
                return "VnlcTokenType::TRUE";
            case TokenType::FALSE:
                return "VnlcTokenType::FALSE";
            case TokenType::IMPORT:
                return "VnlcTokenType::IMPORT";
            case TokenType::EXPORT:
                return "VnlcTokenType::EXPORT";
            case TokenType::AS:
                return "VnlcTokenType::AS";
            case TokenType::MODULE:
                return "VnlcTokenType::MODULE";
            case TokenType::PARENT:
                return "VnlcTokenType::PARENT";
            case TokenType::LAMBDA:
                return "VnlcTokenType::LAMBDA";
            case TokenType::COMMAND:
                return "VnlcTokenType::COMMAND";
            case TokenType::ASYNC:
                return "VnlcTokenType::ASYNC";
            case TokenType::AWAIT:
                return "VnlcTokenType::AWAIT";
            case TokenType::GENERATOR:
                return "VnlcTokenType::GENERATOR";
            case TokenType::YIELD:
                return "VnlcTokenType::YIELD";
            case TokenType::FROM:
                return "VnlcTokenType::FROM";
            case TokenType::DECORATOR:
                return "VnlcTokenType::DECORATOR";
            case TokenType::DECORATE:
                return "VnlcTokenType::DECORATE";
            case TokenType::PANIC:
                return "VnlcTokenType::PANIC";
            case TokenType::ASSERT:
                return "VnlcTokenType::ASSERT";
            case TokenType::TYPEOF:
                return "VnlcTokenType::TYPEOF";
            case TokenType::DEFER:
                return "VnlcTokenType::DEFER";
            case TokenType::ASSET:
                return "VnlcTokenType::ASSET";
            case TokenType::DEFINE:
                return "VnlcTokenType::DEFINE";
            case TokenType::METADATA:
                return "VnlcTokenType::METADATA";
            case TokenType::PLUS:
                return "VnlcTokenType::PLUS";
            case TokenType::MINUS:
                return "VnlcTokenType::MINUS";
            case TokenType::ASTERISK:
                return "VnlcTokenType::ASTERISK";
            case TokenType::SLASH:
                return "VnlcTokenType::SLASH";
            case TokenType::DOUBLE_SLASH:
                return "VnlcTokenType::DOUBLE_SLASH";
            case TokenType::PERCENT:
                return "VnlcTokenType::PERCENT";
            case TokenType::DOUBLE_ASTERISK:
                return "VnlcTokenType::DOUBLE_ASTERISK";
            case TokenType::PLUS_EQUAL:
                return "VnlcTokenType::PLUS_EQUAL";
            case TokenType::MINUS_EQUAL:
                return "VnlcTokenType::MINUS_EQUAL";
            case TokenType::ASTERISK_EQUAL:
                return "VnlcTokenType::ASTERISK_EQUAL";
            case TokenType::SLASH_EQUAL:
                return "VnlcTokenType::SLASH_EQUAL";
            case TokenType::DOUBLE_SLASH_EQUAL:
                return "VnlcTokenType::DOUBLE_SLASH_EQUAL";
            case TokenType::PERCENT_EQUAL:
                return "VnlcTokenType::PERCENT_EQUAL";
            case TokenType::DOUBLE_ASTERISK_EQUAL:
                return "VnlcTokenType::DOUBLE_ASTERISK_EQUAL";
            case TokenType::EQUAL:
                return "VnlcTokenType::EQUAL";
            case TokenType::DOUBLE_QUESTION_EQUAL:
                return "VnlcTokenType::DOUBLE_QUESTION_EQUAL";
            case TokenType::DOUBLE_EQUAL:
                return "VnlcTokenType::DOUBLE_EQUAL";
            case TokenType::EXCLAMATION_EQUAL:
                return "VnlcTokenType::EXCLAMATION_EQUAL";
            case TokenType::RIGHT_ANGLE:
                return "VnlcTokenType::RIGHT_ANGLE";
            case TokenType::RIGHT_ANGLE_EQUAL:
                return "VnlcTokenType::RIGHT_ANGLE_EQUAL";
            case TokenType::LEFT_ANGLE:
                return "VnlcTokenType::LEFT_ANGLE";
            case TokenType::LEFT_ANGLE_EQUAL:
                return "VnlcTokenType::LEFT_ANGLE_EQUAL";
            case TokenType::DOUBLE_AMPERSAND:
                return "VnlcTokenType::DOUBLE_AMPERSAND";
            case TokenType::DOUBLE_PIPE:
                return "VnlcTokenType::DOUBLE_PIPE";
            case TokenType::DOUBLE_QUESTION:
                return "VnlcTokenType::DOUBLE_QUESTION";
            case TokenType::EXCLAMATION:
                return "VnlcTokenType::EXCLAMATION";
            case TokenType::ARROW:
                return "VnlcTokenType::ARROW";
            case TokenType::AMPERSAND:
                return "VnlcTokenType::AMPERSAND";
            case TokenType::PIPE:
                return "VnlcTokenType::PIPE";
            case TokenType::CARET:
                return "VnlcTokenType::CARET";
            case TokenType::TILDE:
                return "VnlcTokenType::TILDE";
            case TokenType::DOUBLE_LEFT_ANGLE:
                return "VnlcTokenType::DOUBLE_LEFT_ANGLE";
            case TokenType::DOUBLE_RIGHT_ANGLE:
                return "VnlcTokenType::DOUBLE_RIGHT_ANGLE";
            case TokenType::TRIPLE_RIGHT_ANGLE:
                return "VnlcTokenType::TRIPLE_RIGHT_ANGLE";
            case TokenType::AMPERSAND_EQUAL:
                return "VnlcTokenType::AMPERSAND_EQUAL";
            case TokenType::PIPE_EQUAL:
                return "VnlcTokenType::PIPE_EQUAL";
            case TokenType::CARET_EQUAL:
                return "VnlcTokenType::CARET_EQUAL";
            case TokenType::DOUBLE_LEFT_ANGLE_EQUAL:
                return "VnlcTokenType::DOUBLE_LEFT_ANGLE_EQUAL";
            case TokenType::DOUBLE_RIGHT_ANGLE_EQUAL:
                return "VnlcTokenType::DOUBLE_RIGHT_ANGLE_EQUAL";
            case TokenType::TRIPLE_RIGHT_ANGLE_EQUAL:
                return "VnlcTokenType::TRIPLE_RIGHT_ANGLE_EQUAL";
            case TokenType::DOT:
                return "VnlcTokenType::DOT";
            case TokenType::COMMA:
                return "VnlcTokenType::COMMA";
            case TokenType::SEMICOLON:
                return "VnlcTokenType::SEMICOLON";
            case TokenType::COLON:
                return "VnlcTokenType::COLON";
            case TokenType::DOUBLE_COLON:
                return "VnlcTokenType::DOUBLE_COLON";
            case TokenType::QUESTION:
                return "VnlcTokenType::QUESTION";
            case TokenType::QUESTION_DOT:
                return "VnlcTokenType::QUESTION_DOT";
            case TokenType::EXCLAMATION_DOT:
                return "VnlcTokenType::EXCLAMATION_DOT";
            case TokenType::DOUBLE_DOT:
                return "VnlcTokenType::DOUBLE_DOT";
            case TokenType::TRIPLE_DOT:
                return "VnlcTokenType::TRIPLE_DOT";
            case TokenType::LEFT_PARENTHESIS:
                return "VnlcTokenType::LEFT_PARENTHESIS";
            case TokenType::RIGHT_PARENTHESIS:
                return "VnlcTokenType::RIGHT_PARENTHESIS";
            case TokenType::LEFT_BRACE:
                return "VnlcTokenType::LEFT_BRACE";
            case TokenType::RIGHT_BRACE:
                return "VnlcTokenType::RIGHT_BRACE";
            case TokenType::LEFT_BRACKET:
                return "VnlcTokenType::LEFT_BRACKET";
            case TokenType::RIGHT_BRACKET:
                return "VnlcTokenType::RIGHT_BRACKET";
            case TokenType::SELECTOR_PREFIX:
                return "VnlcTokenType::SELECTOR_PREFIX";
            case TokenType::INTERPOLATION_START:
                return "VnlcTokenType::INTERPOLATION_START";
            case TokenType::SINGLE_LINE_COMMENT:
                return "VnlcTokenType::SINGLE_LINE_COMMENT";
            case TokenType::MULTI_LINE_COMMENT:
                return "VnlcTokenType::MULTI_LINE_COMMENT";
            case TokenType::BLANK:
                return "VnlcTokenType::BLANK";
            case TokenType::NEWLINE:
                return "VnlcTokenType::NEWLINE";
            case TokenType::LEXICAL_ERROR:
                return "VnlcTokenType::LEXICAL_ERROR";
            case TokenType::END_OF_FILE:
                return "VnlcTokenType::END_OF_FILE";
            default:
                return "Unknown VnlcTokenType";
        }
    }

    bool TokenTypeUtil::isGeneralizedIdentifier(TokenType type) {
        if (type == TokenType::IDENTIFIER) {
            return true;
        }

        bool isKeyword = false;

        for (auto& [keyword, keywordType] : Lexer::keywords) {
            if (type == keywordType) {
                isKeyword = true;
                break;
            }
        }

        return isKeyword;
    }
} // namespace vnlc
