#ifndef VNLC_SYMBOL_ACCESS_MODIFIER_HPP
#define VNLC_SYMBOL_ACCESS_MODIFIER_HPP

enum class VnlcSymbolAccessModifier {
    PUBLIC,
    PROTECTED,
    PRIVATE,
};

#endif // VNLC_SYMBOL_ACCESS_MODIFIER_HPP
