add_executable(
    vnlc
    main.cpp
    app/App.cpp
    lexer/Lexer.cpp
    log/Logger.cpp
    session/Session.cpp
    token/Token.cpp
    util/RunningModeUtil.cpp
    util/TokenTypeUtil.cpp
    ast/AstNode.cpp
    ast/module/ModuleNode.cpp
    ast/expression/BinaryExpressionNode.cpp
    ast/expression/ConditionalExpressionNode.cpp
    ast/expression/ExpressionNode.cpp
    ast/expression/FunctionCallExpressionNode.cpp
    ast/expression/IdentifierExpressionNode.cpp
    ast/expression/LiteralExpressionNode.cpp
    ast/expression/MemberAccessExpressionNode.cpp
    ast/expression/PrimaryExpressionNode.cpp
    ast/expression/RangeExpressionNode.cpp
    ast/expression/SubscriptExpressionNode.cpp
    ast/expression/UnaryExpressionNode.cpp
    ast/expression/StringLiteralExpressionNode.cpp
    ast/expression/SimpleLiteralExpressionNode.cpp
    ast/expression/ListLikeLiteralExpressionNode.cpp
    ast/expression/DictLiteralExpressionNode.cpp
    ast/expression/SelectorLiteralExpressionNode.cpp
    ast/expression/ThisExpressionNode.cpp
    ast/expression/SuperExpressionNode.cpp
    ast/declaration/DeclarationNode.cpp
    ast/declaration/TypeDeclarationNode.cpp
    ast/declaration/FunctionDeclarationNode.cpp
    ast/declaration/ValueDeclarationNode.cpp
    ast/declaration/TypeAliasDeclarationNode.cpp
    ast/declaration/ClassDeclarationNode.cpp
    ast/declaration/InterfaceDeclarationNode.cpp
    ast/declaration/EnumMemberDeclarationNode.cpp
    ast/declaration/EnumDeclarationNode.cpp
    ast/declaration/ImportDeclarationNode.cpp
    ast/declaration/ExportDeclarationNode.cpp
    ast/statement/StatementNode.cpp
    ast/statement/BlockStatementNode.cpp
    ast/statement/ExpressionStatementNode.cpp
    ast/statement/VariableDeclarationStatementNode.cpp
    ast/statement/ControlFlowStatementNode.cpp
    ast/statement/IfStatementNode.cpp
    ast/statement/LoopStatementNode.cpp
    ast/statement/WhileStatementNode.cpp
    ast/statement/ForStatementNode.cpp
    ast/statement/ReturnStatementNode.cpp
    ast/statement/BreakStatementNode.cpp
    ast/statement/ContinueStatementNode.cpp
    ast/statement/ReloadStatementNode.cpp
    ast/statement/SwitchStatementNode.cpp
    ast/type/TypeNode.cpp
    ast/identifier/IdentifierNode.cpp
    parser/Parser.cpp
    diagnostic/Diagnostic.cpp
    symbol/Symbol.cpp
    semantic/SemanticContext.cpp
    semantic/SemanticAnalysisResult.cpp
    semantic/SemanticAnalyzer.cpp
    scope/Scope.cpp
    type/SemanticType.cpp
    type/PrimitiveType.cpp
    type/CustomizedType.cpp
    type/VoidType.cpp
    type/TypeExpressionType.cpp
    type/typeinf/TypeInferenceResult.cpp
    metadata/MetadataInfo.cpp
    vni/import/ImportedItem.cpp
    vni/import/ImportedPackage.cpp
    vni/import/ImportedModule.cpp
    vni/import/ImportedIdentifier.cpp
    vni/import/ImportedLet.cpp
    vni/import/ImportedParameter.cpp
    vni/import/ImportedEnumMember.cpp
    vni/import/ImportedProperty.cpp
    vni/import/ImportedMethod.cpp
    vni/import/ImportedFunc.cpp
    vni/import/ImportedClass.cpp
    vni/import/ImportedInterface.cpp
    vni/import/ImportedEnum.cpp
    vni/import/ImportedEnumValue.cpp
    vni/import/ImportedTypeAlias.cpp
    vni/import/ImportedAlias.cpp
    vni/import/ModuleInterfaceFileReader.cpp
    vni/import/PackageReader.cpp
    vni/export/ModuleInterfaceFileGenerator.cpp
)

target_include_directories(
    vnlc
    PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}"
)

target_link_libraries(
    vnlc
    PRIVATE
    fmt::fmt
    nlohmann_json::nlohmann_json
    CLI11::CLI11
)
