#ifndef VNLC_PARSING_RESULTS_HPP
#define VNLC_PARSING_RESULTS_HPP

#include "parser/synthesized/AdditiveExpressionParsingResult.hpp"           // IWYU pragma: export
#include "parser/synthesized/ArgumentListParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/AssignmentExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/BitwiseAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/BitwiseOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/BitwiseXorExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/BlockStatementParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/BooleanParsingResult.hpp"                      // IWYU pragma: export
#include "parser/synthesized/BreakStatementParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/ClassBodyParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/ClassDeclarationParsingResult.hpp"             // IWYU pragma: export
#include "parser/synthesized/ClassMemberParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/ConditionalExpressionParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/ConstructorParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/ContinueStatementParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/ControlFlowStatementParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/DictEntryParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/DictLiteralParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/EnumAssociatedValueListParsingResult.hpp"      // IWYU pragma: export
#include "parser/synthesized/EnumAssociatedValueParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/EnumBodyParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/EnumDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/EnumMemberDeclarationParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/EqualityExpressionParsingResult.hpp"           // IWYU pragma: export
#include "parser/synthesized/ExponentialExpressionParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/ExportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/ExportListParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/ExpressionParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/ExpressionStatementParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/ForStatementParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/FunctionBodyParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/FunctionDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/FunctionSignatureParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/GenericArgumentListParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/GenericParameterListParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/IdentifierLikeParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/IfStatementParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/ImportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/ImportPathItemParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/ImportPathListParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/ImportPathParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/InterfaceBodyParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/InterfaceDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/InterfaceMethodDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/InterpolationParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/ListLikeLiteralParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/LiteralParsingResult.hpp"                      // IWYU pragma: export
#include "parser/synthesized/LogicalAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/LogicalOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/MetadataParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/MetadataTermParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/ModuleParsingResult.hpp"                       // IWYU pragma: export
#include "parser/synthesized/MultiplicativeExpressionParsingResult.hpp"     // IWYU pragma: export
#include "parser/synthesized/NativeFunctionDeclarationParsingResult.hpp"    // IWYU pragma: export
#include "parser/synthesized/NullishCoalescingExpressionParsingResult.hpp"  // IWYU pragma: export
#include "parser/synthesized/ParameterListParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/ParameterParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/PostfixExpressionParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/PrimaryExpressionParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/PropertyDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/RangeExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/RegularFunctionDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/RelationalExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/ReloadStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/ReturnStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/SelectorArgumentListParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/SelectorArgumentParsingResult.hpp"             // IWYU pragma: export
#include "parser/synthesized/SelectorParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/ShiftExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/StatementParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/StringParsingResult.hpp"                       // IWYU pragma: export
#include "parser/synthesized/SwitchCaseParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/SwitchStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/TopIdentifierDeclarationParsingResult.hpp"     // IWYU pragma: export
#include "parser/synthesized/TypeAliasDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/TypeDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/TypeParsingResult.hpp"                         // IWYU pragma: export
#include "parser/synthesized/UnaryExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VariableDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VariableDeclarationPrimaryParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/VariableDeclarationStatementParsingResult.hpp" // IWYU pragma: export
#include "parser/synthesized/WhileStatementParsingResult.hpp"               // IWYU pragma: export

#endif // VNLC_PARSING_RESULTS_HPP
