#ifndef VNLC_PARSING_RESULTS_HPP
#define VNLC_PARSING_RESULTS_HPP

#include "parser/synthesized/VnlcAdditiveExpressionParsingResult.hpp"           // IWYU pragma: export
#include "parser/synthesized/VnlcArgumentListParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/VnlcAssignmentExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcBitwiseAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcBitwiseOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcBitwiseXorExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcBlockStatementParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/VnlcBooleanParsingResult.hpp"                      // IWYU pragma: export
#include "parser/synthesized/VnlcBreakStatementParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/VnlcClassBodyParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/VnlcClassDeclarationParsingResult.hpp"             // IWYU pragma: export
#include "parser/synthesized/VnlcClassMemberParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/VnlcConditionalExpressionParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/VnlcConstructorParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/VnlcContinueStatementParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcControlFlowStatementParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcDictEntryParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/VnlcDictLiteralParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/VnlcEnumAssociatedValueListParsingResult.hpp"      // IWYU pragma: export
#include "parser/synthesized/VnlcEnumAssociatedValueParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcEnumBodyParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/VnlcEnumDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcEnumMemberDeclarationParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/VnlcEqualityExpressionParsingResult.hpp"           // IWYU pragma: export
#include "parser/synthesized/VnlcExponentialExpressionParsingResult.hpp"        // IWYU pragma: export
#include "parser/synthesized/VnlcExportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcExportListParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/VnlcExpressionParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/VnlcExpressionStatementParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcForStatementParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/VnlcFunctionBodyParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/VnlcFunctionDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcFunctionSignatureParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcGenericArgumentListParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcGenericParameterListParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcIfStatementParsingResult.hpp"                  // IWYU pragma: export
#include "parser/synthesized/VnlcImportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcImportPathItemParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/VnlcImportPathListParsingResult.hpp"               // IWYU pragma: export
#include "parser/synthesized/VnlcImportPathParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/VnlcInterfaceBodyParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/VnlcInterfaceDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcInterfaceMethodDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/VnlcInterpolationParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/VnlcListLikeLiteralParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcLiteralParsingResult.hpp"                      // IWYU pragma: export
#include "parser/synthesized/VnlcLogicalAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcLogicalOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcMetadataParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/VnlcMetadataTermParsingResult.hpp"                 // IWYU pragma: export
#include "parser/synthesized/VnlcModuleParsingResult.hpp"                       // IWYU pragma: export
#include "parser/synthesized/VnlcMultiplicativeExpressionParsingResult.hpp"     // IWYU pragma: export
#include "parser/synthesized/VnlcNativeFunctionDeclarationParsingResult.hpp"    // IWYU pragma: export
#include "parser/synthesized/VnlcNullishCoalescingExpressionParsingResult.hpp"  // IWYU pragma: export
#include "parser/synthesized/VnlcParameterListParsingResult.hpp"                // IWYU pragma: export
#include "parser/synthesized/VnlcParameterParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/VnlcPostfixExpressionParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcPrimaryExpressionParsingResult.hpp"            // IWYU pragma: export
#include "parser/synthesized/VnlcPropertyDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcRangeExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcRegularFunctionDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/VnlcRelationalExpressionParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcReloadStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcReturnStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcSelectorArgumentListParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcSelectorArgumentParsingResult.hpp"             // IWYU pragma: export
#include "parser/synthesized/VnlcSelectorParsingResult.hpp"                     // IWYU pragma: export
#include "parser/synthesized/VnlcShiftExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcStatementParsingResult.hpp"                    // IWYU pragma: export
#include "parser/synthesized/VnlcStringParsingResult.hpp"                       // IWYU pragma: export
#include "parser/synthesized/VnlcSwitchCaseParsingResult.hpp"                   // IWYU pragma: export
#include "parser/synthesized/VnlcSwitchStatementParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcTopIdentifierDeclarationParsingResult.hpp"     // IWYU pragma: export
#include "parser/synthesized/VnlcTypeAliasDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "parser/synthesized/VnlcTypeDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcTypeParsingResult.hpp"                         // IWYU pragma: export
#include "parser/synthesized/VnlcUnaryExpressionParsingResult.hpp"              // IWYU pragma: export
#include "parser/synthesized/VnlcVariableDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "parser/synthesized/VnlcVariableDeclarationPrimaryParsingResult.hpp"   // IWYU pragma: export
#include "parser/synthesized/VnlcVariableDeclarationStatementParsingResult.hpp" // IWYU pragma: export
#include "parser/synthesized/VnlcWhileStatementParsingResult.hpp"               // IWYU pragma: export

#endif // VNLC_PARSING_RESULTS_HPP